### PR TITLE
feat(type): export Config types

### PR DESCRIPTION
**Pull request by perrin4869**
I needed access to the `Config` type in my application

### CODE REVIEW

**Comment by MatteoGioioso** [comment]
@perrin4869 sorry for the late reply, I will try to get on this as soon as I can

**Comment by perrin4869** [comment]
No problems! Take your time :)
Thanks!

**Comment by MatteoGioioso** [comment]
@perrin4869 hello, could you please rename the commit according to semantic versioning? Otherwise `semantic-release` will not trigger the new version. Either rename the commit with amend or just push an empty commit. Thanks

**Comment by perrin4869** [comment]
Done!

**Pull request merged**
